### ISSUE TITLE
Compatibility issue with django_plotly_dash

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/Faraday-liionsden#174]
**Problem**
Adding django_plotly_dash looks like a good route to enabling plots as mentioned in #8. The package dependencies can be resolved by adding `django_plotly_dash` to `requirements.in` as long as: 
a) `requirements.txt` is deleted before using `pip-compile`.
b) the option `--resolver=backtracking` is set. The `docker-compose up --build` command then works and unit tests pass.

**This is the state of affairs at [this point](https://github.com/ImperialCollegeLondon/Faraday-liionsden/tree/3c13590303569eb5113337c24d8dfb84415efd53) and [the unit tests pass in the CI](https://github.com/ImperialCollegeLondon/Faraday-liionsden/actions/runs/3173296571/jobs/5170836138).**

As soon as `INSTALLED_APPS` is updated in `settings.py`, as required by `django_plotly_dash`:

```python
INSTALLED_APPS = [
    ...
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    ...
    ]
```

The following exception is raised: `ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/usr/local/lib/python3.9/site-packages/werkzeug/debug/tbtools.py)`
<details>
<summary>view full traceback</summary>

```python
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
web_1  |     autoreload.raise_last_exception()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
web_1  |     raise _exception[1]
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 398, in execute
web_1  |     autoreload.check_errors(django.setup)()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
web_1  |     app_config = AppConfig.create(entry)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 178, in create
web_1  |     mod = import_module(mod_path)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/__init__.py", line 31, in <module>
web_1  |     from .dash_wrapper import DjangoDash
web_1  |   File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 33, in <module>
web_1  |     import dash
web_1  |   File "/usr/local/lib/python3.9/site-packages/dash/__init__.py", line 5, in <module>
web_1  |     from .dash import Dash, no_update  # noqa: F401,E402
web_1  |   File "/usr/local/lib/python3.9/site-packages/dash/dash.py", line 22, in <module>
web_1  |     from werkzeug.debug.tbtools import get_current_traceback
web_1  | ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/usr/local/lib/python3.9/site-packages/werkzeug/debug/tbtools.py)
```
</details>

This is a common problem, according to [this issue](https://github.com/plotly/dash/issues/1992) and the answer is to roll back to `werkzeug<2.1`. Deleting `requirements.txt` and rerunning `pip-compile` but this time with `--upgrade-package "werkzeug<2.1" results in drastically different `requirements.txt`, including `dash==1.2.0` --> `dash==2.6.2`. 

Adding `'django_plotly_dash.apps.DjangoPlotlyDashConfig',` to `INSTALLED_APPS` now does not reproduce the import error above, but now 93/213 unit tests fail with a similar `psycopg2` error: `psycopg2.InterfaceError: connection already closed`

<details>
<summary>View full traceback</summary>

```python
======================================================================
ERROR: setUpClass (tests.dfndb.test_object_permissions.TestCreatePublic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 236, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/tests/dfndb/test_object_permissions.py", line 72, in setUpClass
    super(TestCreatePublic, self).setUpClass()
  File "/usr/src/app/tests/dfndb/test_object_permissions.py", line 14, in setUpClass
    self.read_only = baker.make_recipe("tests.management.user")
  File "/usr/local/lib/python3.9/site-packages/model_bakery/baker.py", line 199, in make_recipe
    return _recipe(baker_recipe_name).make(
  File "/usr/local/lib/python3.9/site-packages/model_bakery/recipe.py", line 137, in make
    return baker.make(self._model, _using=_using, **self._mapping(_using, defaults))
  File "/usr/local/lib/python3.9/site-packages/model_bakery/baker.py", line 133, in make
    return baker.make(
  File "/usr/local/lib/python3.9/site-packages/model_bakery/baker.py", line 389, in make
    return self._make(**params)
  File "/usr/local/lib/python3.9/site-packages/model_bakery/baker.py", line 470, in _make
    instance = self.instance(
  File "/usr/local/lib/python3.9/site-packages/model_bakery/baker.py", line 504, in instance
    instance.save(**_save_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1414, in execute_sql
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 237, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 236, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```
</details>

It's unclear to me why this is happening.

- The version of `psycopg2` is unchanged - `psycopg2-binary==v2.9.3` in both cases.
- It is not the addition in `settings.py` that causes the error, just the package dependencies. After removing  `'django_plotly_dash.apps.DjangoPlotlyDashConfig'` from `INSTALLED_APPS` the same 93 tests still fail.
- Pinning the django version to 4.1 when running `pip-compile` does not fix the errors. 

**[Go here to see the failing unit tests in the CI](https://github.com/ImperialCollegeLondon/Faraday-liionsden/actions/runs/3174694437/jobs/5171811449).**

**Proposed solution(s)**
Any help appreciated @cc-a @dalonsoa.

I guess we either need to get `django-plotly-dash` working, find an alternative or not use plotly.

Has anyone seen `InterfaceError: connection already closed` before springing up out of nowhere and knows how to fix them? 

Is there some other approach to resolving the dependencies that I should try? 

It seems the main alternative to `django-plotly-dash` is [django-dash](https://django-dash.readthedocs.io/en/latest/#), which I haven't tested yet but @dalonsoa highlighted this has the GPL license, adding more restrictions that we'd like.

**Comment by dandavies99** [comment]
Closing this for the reasons above - I think we can do without this package.
