### ISSUE TITLE
Error uploading Biologic example file - bio-logic-data-table.tsv

### ISSUE THREAD

**Issue by CWestICL** [ImperialCollegeLondon/Faraday-liionsden#186]
**Describe the issue**
Uploading the example file bio-logic-data-table.tsv with the Biologic parser resulted in IndexError at upload.

**To Reproduce**
Steps to reproduce the behaviour:
1. Uploaded bio-logic-data-table.tsv using the Biologic parser
2. Got an IndexError: list index out of range

**Traceback**
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/battDB/exps/add_data/4/

Django Version: 4.1
Python Version: 3.8.14
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'guardian',
 'bootstrap5',
 'django_better_admin_arrayfield',
 'django_tables2',
 'crispy_forms',
 'crispy_bootstrap5',
 'django_filters',
 'django_cleanup.apps.CleanupConfig',
 'rest_framework',
 'rest_framework.authtoken',
 'storages',
 'django_extensions',
 'mptt',
 'battDB.apps.BattdbConfig',
 'common.apps.CommonConfig',
 'dfndb.apps.DfndbConfig',
 'management.apps.ManagementConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/guardian/mixins.py", line 213, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/src/app/battDB/views.py", line 162, in post
    form.instance.full_clean()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1471, in full_clean
    self.clean()
  File "/usr/src/app/battDB/models.py", line 578, in clean
    parsed_file = parse_data_file(file_obj, file_format, columns=cols)
  File "/usr/src/app/parsing_engines/parsing_engines_base.py", line 241, in parse_data_file
    engine = get_parsing_engine(file_format).factory(file_obj)
  File "/usr/src/app/parsing_engines/biologic_engine.py", line 49, in factory
    file_metadata = get_file_header(file_obj, skip_rows, cls.encoding)
  File "/usr/src/app/parsing_engines/biologic_engine.py", line 70, in get_file_header
    if type(header[0]) == bytes:

Exception Type: IndexError at /battDB/exps/add_data/4/
Exception Value: list index out of range
```

**Browser:**
 Chrome - Version 105.0.5195.127 (Official Build) (64-bit)

**Comment by dandavies99** [comment]
This looks like a Biologic data file with no header. 

**Question for researchers:** Should this type of file be parseable? If so, we need to detect that there is no header and parse the table, if not we need to detect there is no header and not allow it to be uploaded, giving a similar error message to that used in #192
